env: development
server:
  port: 8081

grpc:
  address: ":50051"

database:
    host: localhost
    port: 5432
    user: linkify
    password: linkify
    dbname: linkify
    sslmode: disable
cache:
    redis:
        host: localhost
        port: 6379
security:
  oidc:
    issuer_url: https://np-iam.linkifysoft.com/realms/linkifysoft-dev
    client_id: admin-console
    client_secret: XT87P8Tx3GWvJBUAiLQXyBDo8aqx2GXe
    scopes:
      - openid
      - profile
      - email
messaging:
    redis:
        url: localhost:6379
        max_retries: 5
