env: development
server:
  port: 8080
grpc:
  enabled: true

database:
    host: localhost
    port: 5432
    dbname: example
    user: example
    password: example
security:
  oidc:
    issuer_url: https://<example>
    client_id: <client_id>
    client_secret: <client_id>
    scopes:
      - openid
      - profile
      - email
messaging:
    redis:
        url: localhost:6379
