version: '3.8'

services:
  redis:
    image: "redis/redis-stack"
    container_name: "redis-stack"
    ports:
      - "6379:6379"
      - "8001:8001"
  db:
    image: "postgres:latest"
    container_name: "db"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
